### ISSUE TITLE
gcc 10 编译失败

### ISSUE THREAD

**Issue by kubbo** [ossrs/srs#2196]
**描述(Description)**

> gcc 10 srs 编码失败

1. SRS版本(Version): `4.0.71`
1. SRS的日志如下(Log):
```
gcc -DHAVE_CONFIG_H -Icrypto/include -I./include -I./crypto/include -fPIC  -fPIC -Wall -O4 -fexpensive-optimizations -funroll-loops -I/include -I/tmp/srs/trunk/objs/Platform-Linux-5.8.0-SRS4/openssl-OpenSSL_1_0_2u/_release/include -L.  -L/lib -L/tmp/srs/trunk/objs/Platform-Linux-5.8.0-SRS4/openssl-OpenSSL_1_0_2u/_release/lib -lssl -lcrypto -o crypto/test/cipher_driver crypto/test/cipher_driver.c test/getopt_s.c libsrtp2.a -lcrypto -lcrypto -lcrypto -ldl  -lsrtp2
gcc -DHAVE_CONFIG_H -Icrypto/include -I./include -I./crypto/include -fPIC  -fPIC -Wall -O4 -fexpensive-optimizations -funroll-loops -I/include -I/tmp/srs/trunk/objs/Platform-Linux-5.8.0-SRS4/openssl-OpenSSL_1_0_2u/_release/include -I./test -L.  -L/lib -L/tmp/srs/trunk/objs/Platform-Linux-5.8.0-SRS4/openssl-OpenSSL_1_0_2u/_release/lib -lssl -lcrypto -o crypto/test/datatypes_driver crypto/test/datatypes_driver.c test/util.c libsrtp2.a -lcrypto -lcrypto -lcrypto -ldl  -lsrtp2
/usr/bin/ld: libsrtp2.a(datatypes.o):(.bss+0x0): multiple definition of `bit_string'; /tmp/ccKzizkx.o:(.bss+0x0): first defined here
collect2: error: ld returned 1 exit status
make: *** [Makefile:181: crypto/test/datatypes_driver] Error 1


```
1. SRS的配置如下(Config):
```
无
```

**重现(Replay)**

> 重现Bug的步骤(How to replay bug?)

1. `系统信息如下:`
```text 
gcc -v 
cc version 10.2.0 (Ubuntu 10.2.0-13ubuntu1) 
```

1. `编译`
```shell 
/configure
```

**期望行为(Expect)**

> 编译成功，但出现了如下报错
```text 
SSL_1_0_2u/_release/include -c crypto/replay/rdbx.c -o crypto/replay/rdbx.o
gcc -DHAVE_CONFIG_H -Icrypto/include -I./include -I./crypto/include -fPIC  -fPIC -Wall -O4 -fexpensive-optimizations -funroll-loops -I/include -I/tmp/srs/trunk/objs/Platform-Linux-5.8.0-SRS4/openssl-OpenSSL_1_0_2u/_release/include -c crypto/replay/ut_sim.c -o crypto/replay/ut_sim.o
ar cr libsrtp2.a srtp/srtp.o srtp/ekt.o crypto/cipher/cipher.o crypto/cipher/null_cipher.o crypto/cipher/aes_icm_ossl.o crypto/cipher/aes_gcm_ossl.o crypto/hash/null_auth.o crypto/hash/auth.o crypto/hash/hmac_ossl.o crypto/math/datatypes.o crypto/math/stat.o crypto/kernel/crypto_kernel.o crypto/kernel/alloc.o crypto/kernel/key.o crypto/kernel/err.o crypto/replay/rdb.o crypto/replay/rdbx.o crypto/replay/ut_sim.o
ranlib libsrtp2.a
gcc -DHAVE_CONFIG_H -Icrypto/include -I./include -I./crypto/include -fPIC  -fPIC -Wall -O4 -fexpensive-optimizations -funroll-loops -I/include -I/tmp/srs/trunk/objs/Platform-Linux-5.8.0-SRS4/openssl-OpenSSL_1_0_2u/_release/include -L.  -L/lib -L/tmp/srs/trunk/objs/Platform-Linux-5.8.0-SRS4/openssl-OpenSSL_1_0_2u/_release/lib -lssl -lcrypto -o crypto/test/cipher_driver crypto/test/cipher_driver.c test/getopt_s.c libsrtp2.a -lcrypto -lcrypto -lcrypto -ldl  -lsrtp2
gcc -DHAVE_CONFIG_H -Icrypto/include -I./include -I./crypto/include -fPIC  -fPIC -Wall -O4 -fexpensive-optimizations -funroll-loops -I/include -I/tmp/srs/trunk/objs/Platform-Linux-5.8.0-SRS4/openssl-OpenSSL_1_0_2u/_release/include -I./test -L.  -L/lib -L/tmp/srs/trunk/objs/Platform-Linux-5.8.0-SRS4/openssl-OpenSSL_1_0_2u/_release/lib -lssl -lcrypto -o crypto/test/datatypes_driver crypto/test/datatypes_driver.c test/util.c libsrtp2.a -lcrypto -lcrypto -lcrypto -ldl  -lsrtp2
/usr/bin/ld: libsrtp2.a(datatypes.o):(.bss+0x0): multiple definition of `bit_string'; /tmp/ccKzizkx.o:(.bss+0x0): first defined here

```

**Comment by kubbo** [comment]
The root cause is the encoding error of libsrtp under gcc 10. libsrtp has been fixed: https://github.com/cisco/libsrtp/pull/486

`TRANS_BY_GPT3`

**Comment by IreneLu12** [comment]
> The root cause is the encoding error of libsrtp under gcc 10, and libsrtp has been fixed: [cisco/libsrtp#486](https://github.com/cisco/libsrtp/pull/486)

Hello, may I ask what is the final solution?
I am compiling with the latest version of 4.0 release on Arch Linux (Manjaro) system, but I still encounter this error and the compilation fails.
Command: ./configure --with-srt --cubie

```
...
gcc -DHAVE_CONFIG_H -Icrypto/include -I./include -I./crypto/include  -fPIC -Wall -pedantic -Wstrict-prototypes -O4 -fexpensive-optimizations -funroll-loops -I/home/lu/git/srs/trunk/objs/Platform-Linux-5.10.26-GCC10.2.0-SRS4/openssl-1.1-fit/_release/include  -I./test -L.  -o crypto/test/datatypes_driver crypto/test/datatypes_driver.c test/util.c libsrtp2.a -L/home/lu/git/srs/trunk/objs/Platform-Linux-5.10.26-GCC10.2.0-SRS4/openssl-1.1-fit/_release/lib -lcrypto -ldl   -lsrtp2
/usr/bin/ld: libsrtp2.a(datatypes.o):(.bss+0x0): multiple definition of 'bit_string'; /tmp/ccvYcE3f.o:(.bss+0x0): first defined here
collect2: error: ld returned 1 exit status
make: *** [Makefile:215: crypto/test/datatypes_driver] Error 1
Build libsrtp-2-fit failed, ret=2
```

`TRANS_BY_GPT3`

**Comment by sshsu** [comment]
> The root cause is the encoding error issue of libsrtp under gcc 10, which has been fixed: [cisco/libsrtp#486](https://github.com/cisco/libsrtp/pull/486)
> 
> Hello, may I know what is the final solution?
> I am using the latest version of 4.0 release for compilation under Arch Linux (Manjaro) system, but I still encounter this error and the compilation fails.
> Command: ./configure --with-srt --cubie
> 
> ```
> ...
> gcc -DHAVE_CONFIG_H -Icrypto/include -I./include -I./crypto/include  -fPIC -Wall -pedantic -Wstrict-prototypes -O4 -fexpensive-optimizations -funroll-loops -I/home/lu/git/srs/trunk/objs/Platform-Linux-5.10.26-GCC10.2.0-SRS4/openssl-1.1-fit/_release/include  -I./test -L.  -o crypto/test/datatypes_driver crypto/test/datatypes_driver.c test/util.c libsrtp2.a -L/home/lu/git/srs/trunk/objs/Platform-Linux-5.10.26-GCC10.2.0-SRS4/openssl-1.1-fit/_release/lib -lcrypto -ldl   -lsrtp2
> /usr/bin/ld: libsrtp2.a(datatypes.o):(.bss+0x0): multiple definition of 'bit_string'; /tmp/ccvYcE3f.o:(.bss+0x0): first defined here
> collect2: error: ld returned 1 exit status
> make: *** [Makefile:215: crypto/test/datatypes_driver] Error 1
> Build libsrtp-2-fit failed, ret=2
> ```

I'm not sure how SRS pulls in the SRTP library, but it seems like it directly copies the SRTP into SRS without using submodules or external links for updates. Therefore, the simplest method would be to fix this issue in SRTP and then make the necessary modifications accordingly. You just need to change the definition of `bit_string` in `crypto/math/datatypes.h` to `static`.

`TRANS_BY_GPT3`

**Comment by wwng2333** [comment]
> > > The root cause is the encoding error issue of libsrtp under gcc 10, which has been fixed: [cisco/libsrtp#486](https://github.com/cisco/libsrtp/pull/486)
> > 
> > 
> > Hello, may I know what was the final solution?
> > I tried compiling with the latest version 4.0 release on Arch Linux (Manjaro) system, but I still encountered this error and the compilation did not pass.
> > Command: ./configure --with-srt --cubie
> > ```
> > ...
> > gcc -DHAVE_CONFIG_H -Icrypto/include -I./include -I./crypto/include  -fPIC -Wall -pedantic -Wstrict-prototypes -O4 -fexpensive-optimizations -funroll-loops -I/home/lu/git/srs/trunk/objs/Platform-Linux-5.10.26-GCC10.2.0-SRS4/openssl-1.1-fit/_release/include  -I./test -L.  -o crypto/test/datatypes_driver crypto/test/datatypes_driver.c test/util.c libsrtp2.a -L/home/lu/git/srs/trunk/objs/Platform-Linux-5.10.26-GCC10.2.0-SRS4/openssl-1.1-fit/_release/lib -lcrypto -ldl   -lsrtp2
> > /usr/bin/ld: libsrtp2.a(datatypes.o):(.bss+0x0): multiple definition of 'bit_string'; /tmp/ccvYcE3f.o:(.bss+0x0): first defined here
> > collect2: error: ld returned 1 exit status
> > make: *** [Makefile:215: crypto/test/datatypes_driver] Error 1
> > Build libsrtp-2-fit failed, ret=2
> > ```
> 
> I'm not quite sure how SRS pulls in the SRTP library, but it seems like it directly copies the SRTP into SRS without using submodules or external links for updates. In that case, the simplest method would be to fix this issue in the SRTP itself and then make the necessary modifications accordingly. You just need to change the definition of `bit_string` in `crypto/math/datatypes.h` to `static`.

> Perfect solution, thank you for sharing.

`TRANS_BY_GPT3`

**Comment by Frikster** [comment]
> > > The root cause is the encoding error issue of libsrtp under gcc 10, which has been fixed: [cisco/libsrtp#486](https://github.com/cisco/libsrtp/pull/486)
> > 
> > 
> > Hello, may I know what was the final solution?
> > I tried compiling with the latest version 4.0 release on Arch Linux (Manjaro) system, but I still encountered this error and the compilation did not pass.
> > Command: ./configure --with-srt --cubie
> > ```
> > ...
> > gcc -DHAVE_CONFIG_H -Icrypto/include -I./include -I./crypto/include  -fPIC -Wall -pedantic -Wstrict-prototypes -O4 -fexpensive-optimizations -funroll-loops -I/home/lu/git/srs/trunk/objs/Platform-Linux-5.10.26-GCC10.2.0-SRS4/openssl-1.1-fit/_release/include  -I./test -L.  -o crypto/test/datatypes_driver crypto/test/datatypes_driver.c test/util.c libsrtp2.a -L/home/lu/git/srs/trunk/objs/Platform-Linux-5.10.26-GCC10.2.0-SRS4/openssl-1.1-fit/_release/lib -lcrypto -ldl   -lsrtp2
> > /usr/bin/ld: libsrtp2.a(datatypes.o):(.bss+0x0): multiple definition of 'bit_string'; /tmp/ccvYcE3f.o:(.bss+0x0): first defined here
> > collect2: error: ld returned 1 exit status
> > make: *** [Makefile:215: crypto/test/datatypes_driver] Error 1
> > Build libsrtp-2-fit failed, ret=2
> > ```
> 
> I'm not quite sure how SRS pulls in the SRTP library, but it seems like it directly copies the SRTP into SRS without using submodules or external links for updates. In that case, the simplest method would be to fix this issue in the SRTP itself and then make the necessary modifications accordingly. You just need to change the definition of `bit_string` in `crypto/math/datatypes.h` to `static`.

Sorry but how do I change the definition of bit_string to static in `crypto/math/datatypes.h`? I have the same issue as @kubbo 

`TRANS_BY_GPT3`

**Comment by lxlenovostar** [comment]
I have switched to a new version of the libsrtp library and successfully compiled it.

`TRANS_BY_GPT3`
