### ISSUE TITLE
HLS: 转hls输出时出现的问题

### ISSUE THREAD

**Issue by jamesDeng** [ossrs/srs#894]
使用源码分支3.0release安装
运行命令：`./objs/srs -c ./conf/http.hls.conf`
配制文件为默认，并没有修改
操作系统为MAC

使用推流命令：
```
ffmpeg -f avfoundation -framerate 30 -i "1:0" \-f avfoundation -framerate 30 -video_size 640x480 -i "0" \-c:v libx264 -preset ultrafast \-filter_complex 'overlay=main_w-overlay_w-10:main_h-overlay_h-10' -acodec libmp3lame -ar 44100 -ac 1  -f flv rtmp://192.168.1.250:1935/live/livestream
```

log输出为以下：
```
[2017-05-17 17:25:37.675][Trace][20034][109] Drop ts segment, sequence_no=49, uri=livestream-49.ts, duration=82368ms
[2017-05-17 17:25:37.799][Trace][20034][109] Drop ts segment, sequence_no=49, uri=livestream-49.ts, duration=83011ms
[2017-05-17 17:25:38.400][Trace][20034][109] Drop ts segment, sequence_no=49, uri=livestream-49.ts, duration=83675ms
[2017-05-17 17:25:38.454][Trace][20034][109] Drop ts segment, sequence_no=49, uri=livestream-49.ts, duration=83685ms
[2017-05-17 17:25:38.582][Trace][20034][109] Drop ts segment, sequence_no=49, uri=livestream-49.ts, duration=83761ms
[2017-05-17 17:25:38.871][Trace][20034][109] <- CPB time=89726, okbps=0,0,0, ikbps=3176,2993,0, mr=0/350, p1stpt=20000, pnt=5000
[2017-05-17 17:25:39.222][Trace][20034][109] Drop ts segment, sequence_no=49, uri=livestream-49.ts, duration=84305ms
[2017-05-17 17:25:39.257][Trace][20034][109] Drop ts segment, sequence_no=49, uri=livestream-49.ts, duration=84315ms
[2017-05-17 17:25:39.339][Trace][20034][109] Drop ts segment, sequence_no=49, uri=livestream-49.ts, duration=84326ms
[2017-05-17 17:25:39.391][Trace][20034][109] Drop ts segment, sequence_no=49, uri=livestream-49.ts, duration=84335ms
[2017-05-17 17:25:39.911][Trace][20034][109] Drop ts segment, sequence_no=49, uri=livestream-49.ts, duration=84345ms
[2017-05-17 17:25:39.948][Trace][20034][109] Drop ts segment, sequence_no=49, uri=livestream-49.ts, duration=84356ms
[2017-05-17 17:25:40.022][Trace][20034][109] Drop ts segment, sequence_no=49, uri=livestream-49.ts, duration=84933ms
[2017-05-17 17:25:40.094][Trace][20034][109] Drop ts segment, sequence_no=49, uri=livestream-49.ts, duration=84976ms
[2017-05-17 17:25:40.704][Trace][20034][109] Drop ts segment, sequence_no=49, uri=livestream-49.ts, duration=85719ms
[2017-05-17 17:25:40.778][Trace][20034][109] Drop ts segment, sequence_no=49, uri=livestream-49.ts, duration=85729ms
[2017-05-17 17:25:40.849][Trace][20034][109] Drop ts segment, sequence_no=49, uri=livestream-49.ts, duration=85773ms
[2017-05-17 17:25:40.879][Trace][20034][109] Drop ts segment, sequence_no=49, uri=livestream-49.ts, duration=85783ms
```

ts 文件夹为：
<img width="527" alt="wx20170517-172936 2x" src="https://cloud.githubusercontent.com/assets/4443650/26147538/727e9a8e-3b26-11e7-8f6f-9330e8892286.png">
[感觉是创建5个ts文件之后就出问题了，hls流也无法播放，该问题使用别的推流命令时没有出现

**Comment by winlinvip** [comment]
It's ordinarily the problem of stream, please use `./objs/research/librtmp/srs_rtmp_dump` to record a segment of your stream and attach it here, need to do some analysis.

**Comment by jamesDeng** [comment]
@winlinvip I don't have any research under my objs.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
`./configure --with-librtmp`

**Comment by johnwang777** [comment]
Pushing to the same address, even after disconnecting and pushing again, will still have this problem.

The reason is that when SrsHls::on_unpublish is called, SrsHls::aac_samples is not reset to 0. When pushing again, the current segment duration is the total duration of the previous stream, which will be continuously discarded due to the segment being too long.

The solution is to set SrsHls::aac_samples to 0 in SrsHls::on_unpublish.

`TRANS_BY_GPT3`

**Comment by nanguantong** [comment]
The solution is to set `SrsHls::aac_samples` to 0 in `SrsHls::on_unpublish`.

Resolved.

`TRANS_BY_GPT3`

**Comment by nanguantong** [comment]
However, when streaming to the same address, if the connection is disconnected and then reestablished, there will be screen flickering (encoding parameters have changed).

`TRANS_BY_GPT3`

**Comment by xialixin** [comment]
I have also encountered the same issue during the 3.0.25 process. Following the instructions above did indeed solve the problem for the next streaming session, but it did not completely resolve the issue. During the testing process, after streaming and re-encoding, the generation of ts slices still took too long and resulted in failure. Currently, the dts is calculated based on the number of on_audio callbacks. If the on_audio callback count is inaccurate, the dts will be incorrect. Later, I modified the code based on the old version, calculating the dts using timestamps. The modified code is as follows:

    // Use the diff to guess whether the samples is 1024 or 960.
    int nb_samples_per_frame = 1024;
    int diff = ::abs((int)(audio->timestamp - previous_audio_dts)) * srs_flv_srates[format->acodec->sound_rate];
    if (diff > 100 && diff < 950) {
        nb_samples_per_frame = 960;
    }
    
    // Recalc the DTS by the samples of AAC.
    int64_t dts = 90000 * aac_samples / srs_flv_srates[format->acodec->sound_rate];
    aac_samples += nb_samples_per_frame;
   
    int64_t dts2 = audio->timestamp * 90; 
    if ((ret = controller->write_audio(format->audio, dts2)) != ERROR_SUCCESS) {
        srs_error("hls cache write audio failed. ret=%d", ret);
        return ret;
    }
    return ret;

After running the test, the transcoded stream also generated ts slices correctly, and there was no need to set SrsHls::aac_samples=0 during SrsHls::on_unpublish. Everything worked fine.

`TRANS_BY_GPT3`

**Comment by chunqiulfq** [comment]
I also encountered the same problem.
The streaming program is a program I developed myself, which directly pushes `h264 + aac` streams.
SRS version: `3.0.97`

Output is:
```
[2020-01-20 17:16:41.487][Trace][28265][449] Drop ts segment, sequence_no=16, uri=duobei_t3-16.ts, duration=2147459042ms
[2020-01-20 17:16:41.613][Trace][28265][449] Drop ts segment, sequence_no=17, uri=duobei_t3-17.ts, duration=2147458922ms
[2020-01-20 17:16:41.647][Trace][28265][449] Drop ts segment, sequence_no=17, uri=duobei_t3-17.ts, duration=2147458882ms
[2020-01-20 17:16:41.686][Trace][28265][449] Drop ts segment, sequence_no=17, uri=duobei_t3-17.ts, duration=2147458842ms
[2020-01-20 17:16:41.727][Trace][28265][449] Drop ts segment, sequence_no=17, uri=duobei_t3-17.ts, duration=2147458802ms
[2020-01-20 17:16:41.767][Trace][28265][449] Drop ts segment, sequence_no=17, uri=duobei_t3-17.ts, duration=2147458762ms
[2020-01-20 17:16:41.787][Trace][28265][449] 48B video sh,  codec(7, profile=High, level=Other, 128x1072, 0kbps, 0.0fps, 0.0s)
[2020-01-20 17:16:41.807][Trace][28265][449] Drop ts segment, sequence_no=17, uri=duobei_t3-17.ts, duration=2147458722ms
[2020-01-20 17:16:41.851][Trace][28265][449] Drop ts segment, sequence_no=17, uri=duobei_t3-17.ts, duration=2147458682ms
[2020-01-20 17:16:41.955][Trace][28265][449] Drop ts segment, sequence_no=17, uri=duobei_t3-17.ts, duration=2147458622ms
[2020-01-20 17:16:41.978][Trace][28265][449] <- CPB time=20004776, okbps=1,0,0, ikbps=2634,0,0, mr=0/350, p1stpt=20000, pnt=5000
[2020-01-20 17:16:41.995][Trace][28265][449] Drop ts segment, sequence_no=17, uri=duobei_t3-17.ts, duration=2147458502ms
[2020-01-20 17:16:42.035][Trace][28265][449] Drop ts segment, sequence_no=17, uri=duobei_t3-17.ts, duration=2147458462ms
[2020-01-20 17:16:42.171][Trace][28265][449] Drop ts segment, sequence_no=17, uri=duobei_t3-17.ts, duration=2147458402ms
[2020-01-20 17:16:42.207][Trace][28265][449] Drop ts segment, sequence_no=17, uri=duobei_t3-17.ts, duration=2147458282ms
[2020-01-20 17:16:42.247][Trace][28265][449] Drop ts segment, sequence_no=17, uri=duobei_t3-17.ts, duration=2147458242ms
[2020-01-20 17:16:42.287][Trace][28265][449] Drop ts segment, sequence_no=17, uri=duobei_t3-17.ts, duration=2147458242ms
[2020-01-20 17:16:42.407][Trace][28265][449] Drop ts segment, sequence_no=18, uri=duobei_t3-18.ts, duration=2147458142ms
[2020-01-20 17:16:42.447][Trace][28265][449] Drop ts segment, sequence_no=18, uri=duobei_t3-18.ts, duration=2147458082ms
[2020-01-20 17:16:42.487][Trace][28265][449] Drop ts segment, sequence_no=18, uri=duobei_t3-18.ts, duration=2147458042ms
```

RTMP streaming is normal, but HLS streaming cannot be pulled.

Check the code, @xialixin's method is already in the code.
``` c++
    // The diff duration in ms between two FLV audio packets.
    int diff = ::abs((int)(audio->timestamp - previous_audio_dts));
    previous_audio_dts = audio->timestamp;

    // Guess the number of samples for each AAC frame.
    // If samples is 1024, the sample-rate is 8000HZ, the diff should be 1024/8000s=128ms.
    // If samples is 1024, the sample-rate is 44100HZ, the diff should be 1024/44100s=23ms.
    // If samples is 2048, the sample-rate is 44100HZ, the diff should be 2048/44100s=46ms.
    int nb_samples_per_frame = 0;
    int guessNumberOfSamples = diff * srs_flv_srates[format->acodec->sound_rate] / 1000;
    if (guessNumberOfSamples > 0) {
        if (guessNumberOfSamples < 960) {
            nb_samples_per_frame = 960;
        } else if (guessNumberOfSamples < 1536) {
            nb_samples_per_frame = 1024;
        } else if (guessNumberOfSamples < 3072) {
            nb_samples_per_frame = 2048;
        } else {
            nb_samples_per_frame = 4096;
        }
    }

    // Recalc the DTS by the samples of AAC.
    aac_samples += nb_samples_per_frame;
    int64_t dts = 90000 * aac_samples / srs_flv_srates[format->acodec->sound_rate];

    // If directly turn FLV timestamp, overwrite the guessed DTS.
    // @doc https://github.com/ossrs/srs/issues/1506#issuecomment-562063095
    if (hls_dts_directly) {
        dts = audio->timestamp * 90;
    }

    if ((err = controller->write_audio(format->audio, dts)) != srs_success) {
        return srs_error_wrap(err, "hls: write audio");
    }
```

Setting `SrsHls::aac_samples=0` in `SrsHls::on_unpublish` did not have any effect.

So I tested version `2.0.263`, and the output was:
```
[2020-01-20 17:36:09.881][trace][1705][111] audio drop ts segment, sequence_no=0, uri=duobei_t3-0.ts, duration=2147483.63, start=360
[2020-01-20 17:36:09.959][trace][1705][111] audio drop ts segment, sequence_no=0, uri=duobei_t3-0.ts, duration=2147483.61, start=360
[2020-01-20 17:36:09.999][trace][1705][111] audio drop ts segment, sequence_no=0, uri=duobei_t3-0.ts, duration=2147483.63, start=360
[2020-01-20 17:36:10.039][trace][1705][111] audio drop ts segment, sequence_no=0, uri=duobei_t3-0.ts, duration=2147483.63, start=360
[2020-01-20 17:36:10.079][trace][1705][111] audio drop ts segment, sequence_no=0, uri=duobei_t3-0.ts, duration=2147483.63, start=360
[2020-01-20 17:36:10.121][trace][1705][111] audio drop ts segment, sequence_no=0, uri=duobei_t3-0.ts, duration=2147483.63, start=360
[2020-01-20 17:36:10.159][trace][1705][111] audio drop ts segment, sequence_no=0, uri=duobei_t3-0.ts, duration=2147483.63, start=360
[2020-01-20 17:36:10.250][trace][1705][111] audio drop ts segment, sequence_no=0, uri=duobei_t3-0.ts, duration=2147483.61, start=360
[2020-01-20 17:36:10.251][warn][1705][111][11] hls timestamp jump 193273526880=>360
[2020-01-20 17:36:10.339][trace][1705][111] audio drop ts segment, sequence_no=0, uri=duobei_t3-0.ts, duration=2147483.61, start=360
[2020-01-20 17:36:10.371][warn][1705][111][11] hls timestamp jump 193273526880=>615600
[2020-01-20 17:36:10.396][trace][1705][111] audio drop ts segment, sequence_no=0, uri=duobei_t3-0.ts, duration=2147476.77, start=615600
[2020-01-20 17:36:10.422][warn][1705][111][11] hls timestamp jump 193273526880=>619200
[2020-01-20 17:36:10.435][trace][1705][111] audio drop ts segment, sequence_no=0, uri=duobei_t3-0.ts, duration=2147476.73, start=619200
[2020-01-20 17:36:10.435][warn][1705][111][11] hls timestamp jump 193273526880=>360
[2020-01-20 17:36:10.482][trace][1705][111] audio drop ts segment, sequence_no=0, uri=duobei_t3-0.ts, duration=2147483.63, start=360
[2020-01-20 17:36:10.519][trace][1705][111] audio drop ts segment, sequence_no=0, uri=duobei_t3-0.ts, duration=2147483.63, start=360
[2020-01-20 17:36:10.601][trace][1705][111] audio drop ts segment, sequence_no=0, uri=duobei_t3-0.ts, duration=2147483.61, start=360
```

Before sending the RTMP packet in the streaming program, I printed the timestamp in this RTMP packet and found that the timestamp was correct.

I want to know if this is a problem with my streaming program or with SRS.

`TRANS_BY_GPT3`

**Comment by mapengfei53** [comment]
`srs_error_t SrsHls::on_audio(SrsSharedPtrMessage* shared_audio, SrsFormat* format)
{
    srs_error_t err = srs_success;
    
    // Ignore if no format->acodec, it means the codec is not parsed, or unknown codec.
    // @issue https://github.com/ossrs/srs/issues/1506#issuecomment-562079474
    if (!format->acodec) {
        return err;
    }
    
    // update the hls time, for hls_dispose.
    last_update_time = srs_get_system_time();
    
    SrsSharedPtrMessage* audio = shared_audio->copy();
    SrsAutoFree(SrsSharedPtrMessage, audio);

    // ts support audio codec: aac/mp3
    SrsAudioCodecId acodec = format->acodec->id;
    if (acodec != SrsAudioCodecIdAAC && acodec != SrsAudioCodecIdMP3) {
        return err;
    }
    
    // TODO: FIXME: config the jitter of HLS.
    if ((err = jitter->correct(audio, SrsRtmpJitterAlgorithmOFF)) != srs_success) {
        return srs_error_wrap(err, "hls: jitter");
    }
    
    // Reset the aac samples counter when DTS jitter.
    if (previous_audio_dts > audio->timestamp && audio->timestamp != 0) {
        previous_audio_dts = audio->timestamp;
        aac_samples = 0;
    }
    
    // The diff duration in ms between two FLV audio packets.
    int diff = ::abs((int)(audio->timestamp - previous_audio_dts));
    if (audio->timestamp != 0) {
        previous_audio_dts = audio->timestamp;
    }
    
    // Guess the number of samples for each AAC frame.
    // If samples is 1024, the sample-rate is 8000HZ, the diff should be 1024/8000s=128ms.
    // If samples is 1024, the sample-rate is 44100HZ, the diff should be 1024/44100s=23ms.
    // If samples is 2048, the sample-rate is 44100HZ, the diff should be 2048/44100s=46ms.
    int nb_samples_per_frame = 0;
    int guessNumberOfSamples = diff * srs_flv_srates[format->acodec->sound_rate] / 1000;
    if (guessNumberOfSamples > 0) {
        if (guessNumberOfSamples < 960) {
            nb_samples_per_frame = 960;
        } else if (guessNumberOfSamples < 1536) {
            nb_samples_per_frame = 1024;
        } else if (guessNumberOfSamples < 3072) {
            nb_samples_per_frame = 2048;
        } else {
            nb_samples_per_frame = 4096;
        }
    }
    // Recalc the DTS by the samples of AAC.
    aac_samples += nb_samples_per_frame;
    
    if (!enabled) {
        return err;
    }
    
    int64_t dts = 90000 * aac_samples / srs_flv_srates[format->acodec->sound_rate];
    // ignore sequence header
    srs_assert(format->audio);
    if (acodec == SrsAudioCodecIdAAC && format->audio->aac_packet_type == SrsAudioAacFrameTraitSequenceHeader) {
        return controller->on_sequence_header();
    }
    
    // If directly turn FLV timestamp, overwrite the guessed DTS.
    // @doc https://github.com/ossrs/srs/issues/1506#issuecomment-562063095
    if (hls_dts_directly) {
        dts = audio->timestamp * 90;
    }
    
    if ((err = controller->write_audio(format->audio, dts)) != srs_success) {
        return srs_error_wrap(err, "hls: write audio");
    }
    
    return err;
}`
你把函数修改成这样看看行不行。

**Comment by winlinvip** [comment]
你贴这段代码，我怎么知道你改了什么呢？麻烦你发下PR吧。最好能先分析下问题是什么，我才能理解为什么要这么改。

**Comment by mapengfei53** [comment]
```
// Reset the aac samples counter when DTS jitter.
    if (previous_audio_dts > audio->timestamp && audio->timestamp != 0) {
        previous_audio_dts = audio->timestamp;
        aac_samples = 0;
    }
    
    // The diff duration in ms between two FLV audio packets.
    int diff = ::abs((int)(audio->timestamp - previous_audio_dts));
    if (audio->timestamp != 0) {
        previous_audio_dts = audio->timestamp;
    }
```
主要修改了只有音频时间戳(audio->timestamp != 0)不为零的时候才去重置aac_samples，同时(audio->timestamp != 0)不为零的时候才去将音频时间戳赋值给previous_audio_dts,因为重复推流的话，previous_audio_dts的值肯定大于音频的时间戳，会导致previous_audio_dts被赋值为0.

**Comment by mapengfei53** [comment]
It seems not quite right.

`TRANS_BY_GPT3`

**Comment by chunqiulfq** [comment]
@xialixin what I said is already in the code, it's not that I modified the code, but the code I posted is already in version `3.0.97`.
https://github.com/ossrs/srs/blob/v3.0-a8/trunk/src/app/srs_app_hls.cpp#L1243

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
😄 没事，不着急，开源项目没有PD，我们有足够的时间找到更合适和更好的解法。
